[package]
name = "astral"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-multipart = "0.6"
tokio = {version = "1", features = ["full"]}
rand = "0.8"
